id = "pickls"
name = "Pickls"
version = "0.0.5"
schema_version = 1
authors = ["Will Bradley <williambbradley@gmail.com>"]
description = "Leverage Pickls to handle linting and formatting in Zed"
repository = "https://github.com/wbbradley/pickls-zed"

[language_servers.pickls]
name = "pickls"
# TODO: avoid having to specify this.
languages = [
    "C",
    "C#",
    "C++",
    "CSS",
    "Elixir",
    "Go",
    "HTML",
    "JSON",
    "JSONC",
    "Java",
    "JavaScript",
    "JSON",
    "JSONC",
    "Kotlin",
    "Markdown",
    "Objective-C",
    "PHP",
    "Python",
    "Ruby",
    "Rust",
    "SCSS",
    "SQL",
    "Scala",
    "Shell Script",
    "Swift",
    "TOML",
    "TypeScript",
    "YAML",
]
